### ISSUE TITLE
Не авторизует в яндексе

### ISSUE THREAD

**Issue by lowitea** [dobroweb/rhythmbox-plugin-yandex-music#12]
При открытии программы и нажатия на "мою музыку" вылезает окно для ввода учётных данных с яндекса. При вводе любых данных (как верных так и рандомных) окно закрывается и ничего не происходит. И так после каждого перезапуска ритмбокса. Проверил в dconf там не создаётся папка yandex-music в разделе плагинов ритмбокса.

```
OS: Fedora Linux 36 (Workstation Edition) x86_64
DE: GNOME 42.0
```

**Comment by lowitea** [comment]
И ещё вопрос небольшой, можно где-то увидеть логи выполнения плагина?

**Comment by lowitea** [comment]
Супер, спасибо, с логами повеселее)
Выдал трейс:

```
Traceback (most recent call last):
  File "/home/lowit/.local/share/rhythmbox/plugins/yandex-music/yandex-music.py", line 73, in do_selected
    if self.login_yandex():
  File "/home/lowit/.local/share/rhythmbox/plugins/yandex-music/yandex-music.py", line 96, in login_yandex
    token = Client.generate_token_by_username_and_password(login, password)
AttributeError: type object 'Client' has no attribute 'generate_token_by_username_and_password'
```

Похоже на расхождение версий...

Моя версия yandex-music
```
pip freeze | fgrep yandex     
yandex-music==2.0.1
```

**Comment by dobroweb** [comment]
Обновите версию плагин до 0.2-alpha или с ветки main возьмите посвежее. У вас старая версия плагина под версию 1.0 API yandex-music.

**Comment by lowitea** [comment]
Да, действительно, спасибо за помощь.
Правильно обновил и всё заработало.
Для информации получилось забавно: я раньше ставил версию 0.1, она не работала. Сегодня попытался поставить плагин ещё раз по инструкции. Был уверен что он перезапишет старую версию. Но если использовать команду перемещения из README, когда плагин ранее уже был установлен, новая версия будет размещена в подпапку. То есть путь к новой версии будет `~/.local/share/rhythmbox/plugins/yandex-music/rhythmbox-plugin-yandex-music-0.2-alpha`.
Возможно в readme стоит добавить информацию о том, как правильно обновлять плагин.
