### ISSUE TITLE
Как подгрузить плейлисты

### ISSUE THREAD

**Issue by dimugric** [dobroweb/rhythmbox-plugin-yandex-music#15]
Подскажите, пожалуйста, в проигрываетеле вижу только 1 стандартный плейлист - "Мне нравится" и потоки.
В профиле Я.Музыки имею несколько альтернативных плейлистов, которые в проигрыватель не подтягиваются, хотя в комментариях по уже опубликованным issues так понимаю, они должны быть.
Возможно что-то делаю не так?

**Comment by dobroweb** [comment]
Плейлистов в релизе пока нет. Чтобы использовать этот функционал, необходимо [скачать плагин из ветки main](https://github.com/dobroweb/rhythmbox-plugin-yandex-music/archive/refs/heads/main.zip).

**Comment by dimugric** [comment]
> Плейлистов в релизе пока нет. Чтобы использовать этот функционал, необходимо [скачать плагин из ветки main](https://github.com/dobroweb/rhythmbox-plugin-yandex-music/archive/refs/heads/main.zip).

Полагаю при этом удалить действующий плагин?
Использую на Arch, установленный из AUR

**Comment by dobroweb** [comment]
> 

Можете, в принципе, удалить пакет из AUR, хотя это не обязательно. Rhythmbox будет в первую очередь подключать плагины из `home` пользователя. Пакет из AUR ставит плагин в корневую область.

Хотя может имеет смысл зарелизить плейлисты и обновить пакет в AUR. Давайте так и сделаю. Напишу когда закину в AUR обновление.

**Comment by dobroweb** [comment]
> > Плейлистов в релизе пока нет. Чтобы использовать этот функционал, необходимо [скачать плагин из ветки main](https://github.com/dobroweb/rhythmbox-plugin-yandex-music/archive/refs/heads/main.zip).
> 
> Полагаю при этом удалить действующий плагин? Использую на Arch, установленный из AUR

Обновите пакет из AUR. Должны заработать плейлисты

**Comment by dimugric** [comment]
> Обновите пакет из AUR. Должны заработать плейлисты

Отлично, спасибо!
В AUR пришел свежий релиз. Обновил, плейлисты подгрузились.
Спасибо за Ваш труд
