### ISSUE TITLE
Обложки для треков

### ISSUE THREAD

**Issue by TakovKot** [dobroweb/rhythmbox-plugin-yandex-music#16]
Чудесно было бы подтягивать обложку для трека из я.м или может как-то можно сторонним плагином подтягивать?
![изображение](https://user-images.githubusercontent.com/103324101/170883764-daf82d84-5be8-405c-93c9-d165d7de6b92.png)
Хотелось бы видеть красоту вот в такой ситуации

**Comment by dobroweb** [comment]
Пока не нашёл простого способа подтягивания обложки альбома. Похоже, что у Rhythmbox свой подход к этому. Как я понял API, необходимо самостоятельно кешировать обложку и добавлять в БД обложек. Но точной информации по этому поводу я так и не нашёл. Может я, конечно, ошибаюсь и надо просто правильно отработать со свойством БД `rb:coverArtUri`
