### ISSUE TITLE
Ошибка при загрузке плейлиста

### ISSUE THREAD

**Issue by dburkov05** [dobroweb/rhythmbox-plugin-yandex-music#17]
При наличии более чем 10 плейлистов часть из них не корректно загружается.
![image](https://user-images.githubusercontent.com/26483813/170884823-e3207323-9263-44ad-a0b1-cb47bc8971b9.png)
![image](https://user-images.githubusercontent.com/26483813/170884868-ddedf399-11f0-4298-a86d-044cb1de81b9.png)
![image](https://user-images.githubusercontent.com/26483813/170884899-d288e8e1-536e-487f-8211-3691264d69aa.png)
Судя по всему проблема появилась из-за того в функции load_tracks класса YMFeedSource отбрасываются только первые 6 символов, что приводит к проблеме, в случае двузначного(и более) кол-ва плейлистов.

**Comment by dobroweb** [comment]
Ждал этой ошибки от кого-то, потому что изначально понимал, что неправильно в данном случае поступаю, что пользуютсь фиксированным количеством символов. Поправлю этот момент.

**Comment by dobroweb** [comment]
Устранено в коммите https://github.com/dobroweb/rhythmbox-plugin-yandex-music/commit/5810025e322620be34b4df341d7e2581291cb601
Обновите плагин из ветки `main`, чтобы пользоваться всеми вашими плейлистами
