### ISSUE TITLE
Обновление плагина

### ISSUE THREAD

**Issue by Vlagilen** [dobroweb/rhythmbox-plugin-yandex-music#21]
Не нашел в описании информации о том как обновить плагин? Везде фигурирует ссылка на один и тот же архив "0.3-alpha".

**Comment by lowitea** [comment]
Поделюсь своим способом. В качестве обходного решения, пока плагин в активной разработке можно обновлять прямо из мастера через гит. Для этого я спулил проект в папку с плагинами ритмбокса и когда нужно обновить просто делаю в ней git pull.

**Comment by dobroweb** [comment]
> Не нашел в описании информации о том как обновить плагин? Везде фигурирует ссылка на один и тот же архив "0.3-alpha".

Во всех релизных версиях функционал доведен до какого-то логического завершения или промежуточного звена (в этом случае пишу, что экспериментальная функция). Плюс установка релизной версии не зависит от наличия `git` в системе.

Самый простой вариант иметь самую актуальную (тестовую) сборку плагина, тот, что подсказал @lowitea. То есть клонировать ветку `main` по пути `~/.local/share/rhythmbox/plugins/yandex-music/` и обновлять командой `git pull`

Инструкцию по установке можно передалать тогда так:
```
$ mkdir -p ~/.local/share/rhythmbox/plugins/
$ cd ~/.local/share/rhythmbox/plugins/
$ git clone https://github.com/dobroweb/rhythmbox-plugin-yandex-music.git
$ mv rhythmbox-plugin-yandex-music yandex-music
```

А обновление надо делать так:
```
$ cd ~/.local/share/rhythmbox/plugins/yandex-music/
$ git pull
```

**Comment by Vlagilen** [comment]
Отлично, спасибо.
