### ISSUE TITLE
Не включается плагин

### ISSUE THREAD

**Issue by lenargasimov** [dobroweb/rhythmbox-plugin-yandex-music#5]
Не удаётся активировать плагин в настройках Rhythmbox:

![screen](https://user-images.githubusercontent.com/48679704/162574667-ea2bfaf2-4278-4797-a9c1-38b02530759e.png)
Расположение файлов:

![Снимок экрана от 2022-04-09 15-51-30](https://user-images.githubusercontent.com/48679704/162574878-73d652be-8830-41c8-9ecf-c87289729cc7.png)
Библиотеку [yandex-music-api](https://github.com/MarshalX/yandex-music-api) установил через pip, пробовал через pip3

**Comment by dobroweb** [comment]
Попробуйте запустить Rhythmbox из терминала и активировать/найти в списке плагин. И пришлите, пожалуйста, что программа выдаст в терминале.

**Comment by lenargasimov** [comment]
![Снимок экрана от 2022-04-09 16-37-00](https://user-images.githubusercontent.com/48679704/162576497-0298c76e-5512-42d2-a782-5c1ea70bf0f4.png)

**Comment by dobroweb** [comment]
В данном случае система у вас не видит библиотеку yandex-music-api. Что у вас за дистрибутив?

**Comment by lenargasimov** [comment]
> В данном случае система у вас не видит библиотеку yandex-music-api. Что у вас за дистрибутив?

Ubuntu 20.04.4 LTS

**Comment by dobroweb** [comment]
Может попробовать установить библиотеку непосредственно из git через команду python?
```
git clone https://github.com/MarshalX/yandex-music-api
cd yandex-music-api
python setup.py install
```

**Comment by lenargasimov** [comment]
> Может попробовать установить библиотеку непосредственно из git через команду python?
> 
> ```
> git clone https://github.com/MarshalX/yandex-music-api
> cd yandex-music-api
> python setup.py install
> ```

Попробовал, та же ошибка что на последнем скриншоте

**Comment by dobroweb** [comment]
Попробуйте установить из папки, куда скачалась библиотека, с помощью команды (уточним версию python)
```
python38 setup.py install
```

**Comment by lenargasimov** [comment]
> Попробуйте установить из папки, куда скачалась библиотека, с помощью команды (уточним версию python)
> 
> ```
> python38 setup.py install
> ```
> 
> Или лучше вот так установить
> 
> ```
> python38 -m pip install yandex-music
> ```
ERROR: Could not install packages due to an EnvironmentError: [Errno 30] Read-only file system: '/snap/python38/22/usr/local'

![Снимок экрана от 2022-04-09 19-13-55](https://user-images.githubusercontent.com/48679704/162582268-900bd099-49aa-438c-a23e-526d04b35c29.png)

**Comment by dobroweb** [comment]
Можете написать вывод следующих команд
```
ls /usr/bin/python*
ls /snap/python*
```
В системе много версий питона, Rhythmbox обращается к классической версии python 3.8, а команда python38 ведёт к snap версии пакета. Понять пытаюсь как тогда установить библиотеку в нужную версию питона.

**Comment by lenargasimov** [comment]
> Можете написать вывод следующих команд
> 
> ```
> ls /usr/bin/python*
> ls /snap/python*
> ```
> 
> В системе много версий питона, Rhythmbox обращается к классической версии python 3.8, а команда python38 ведёт к snap версии пакета. Понять пытаюсь как тогда установить библиотеку в нужную версию питона.
![Снимок экрана от 2022-04-09 19-43-43](https://user-images.githubusercontent.com/48679704/162583357-b24b9f6e-e83c-4455-bced-d915d59fb026.png)

**Comment by dobroweb** [comment]
Давайте тогда попробуем вот так установить
```
/usr/bin/python3.8 -m pip install yandex-music
```

**Comment by lenargasimov** [comment]
> Давайте тогда попробуем вот так установить
> 
> ```
> /usr/bin/python3.8 -m pip install yandex-music
> ```

  File "/usr/lib/python3/dist-packages/urllib3/util/queue.py", line 10, in <module>
    class LifoQueue(queue.Queue):
AttributeError: module 'queue' has no attribute 'Queue'

(rhythmbox:9413): libpeas-WARNING **: 20:00:18.392: Error loading plugin 'yandex-music'

(rhythmbox:9413): Gtk-WARNING **: 20:00:21.856: Can't set a parent on widget which has a parent

![Снимок экрана от 2022-04-09 20-00-53](https://user-images.githubusercontent.com/48679704/162583962-34ce4aec-fea4-4eed-8bed-472595c75405.png)

**Comment by dobroweb** [comment]
Попробуйте библиотеку requests ещё установить/обновить
```
python3.8 -m pip install requests --upgrade
```

**Comment by dobroweb** [comment]
Попробовал на виртуальной машине и чистой Ubuntu 20.04 LTS запустить плагин в Rhythmbox.
Для этого на чистой Ubuntu установил pip (почему-то пакет python3-pip ни в какую не захотел устанавливать)
```
$ wget https://bootstrap.pypa.io/get-pip.py
$ python3 get-pip.py
```
модуль yandex-music
```
$ python3 -m pip install yandex-music
```
и данный плагин
```
$ wget https://github.com/dobroweb/rhythmbox-plugin-yandex-music/archive/refs/tags/0.2-alpha.tar.gz
$ tar -zxvf 0.2-alpha.tar.gz
$ mkdir -p ~/.local/share/rhythmbox/plugins/
$ mv rhythmbox-plugin-yandex-music* ~/.local/share/rhythmbox/plugins/yandex-music
```
И всё заработало корректно. Не понимаю тогда что у вас происходит с Python и почему он ругается на стандартный модуль свой.

**Comment by lenargasimov** [comment]
После переустановки Ubuntu 20.04, плагин установился, всё замечательно работает! Спасибо вам за возможность слушать музыку через Rhythmbox.
