### ISSUE TITLE
код подтверждения

### ISSUE THREAD

**Issue by Vital-Vital** [dobroweb/rhythmbox-plugin-yandex-music#50]
при включении плагина выскакивает уведомление "сейчас откроется браузер. скопируйте код (code=<код>) из адресной строки и введите в форму"
Нажимаю "ок" появляется форма для ввода кода, браузер не открывается и ничего более не происходит.
![screen](https://github.com/feschukov/rhythmbox-plugin-yandex-music/assets/124063784/562e54ab-e100-4e40-9e56-db2e2d8b9b92)
![screen2](https://github.com/feschukov/rhythmbox-plugin-yandex-music/assets/124063784/8000f195-86ce-47e1-b209-be9ac4ae4d72)

**Comment by Vital-Vital** [comment]
Разобрался

**Comment by feschukov** [comment]
Добрый день. Подскажите, пожалуйста, что вы сделали для того, чтобы у вас всё заработало? Я немножко не понимаю это проблема плагина или это проблема в настройках вашей операционной системы было?

**Comment by Vital-Vital** [comment]
Приветствую. Я просто ввел в «кол подтверждения» набор букв/цифр и тогда открылся браузер с ссылкой авторизации в яндексе. Оттуда уже скопировал нужный код

**Comment by Vital-Vital** [comment]
*код
