### ISSUE TITLE
Сменить ID

### ISSUE THREAD

**Issue by falinkv** [dobroweb/rhythmbox-plugin-yandex-music#54]
Здравствуйте. 

Пользуюсь плагином уже долго, пока вроде бы без глюков, за исключением смены ID. Хочу войти под другим аккаунтом, а как выйти из этого в плагине не понятно. Опишите механизм пожалуйста

Спасибо.

**Comment by feschukov** [comment]
Добрый день. На текущий момент нет возможности через графический интерфейс сбросить токен. Эту тему обсуждали в ветке https://github.com/feschukov/rhythmbox-plugin-yandex-music/issues/9, там есть команда, как в терминале сбросить токен или через программу dconf-editor.
