### ISSUE TITLE
No modul named yandex-music

### ISSUE THREAD

**Issue by VadimRight** [dobroweb/rhythmbox-plugin-yandex-music#56]
Нет папки Яндекс.Музыка. Зашел в настройки плагинов и там выбрал плагин, но он загорелся красным.
Также в консоли вывел код ошибки, что отсутсвует модуль yandex_music
Использую Fedora
![Screenshot from 2024-03-07 22-48-49](https://github.com/feschukov/rhythmbox-plugin-yandex-music/assets/116267906/9040e8f1-1693-44d9-bba8-2fdd28351196)
![Screenshot from 2024-03-07 22-51-29](https://github.com/feschukov/rhythmbox-plugin-yandex-music/assets/116267906/c30492e0-9c96-447d-a56d-ff0e27072eb4)

**Comment by feschukov** [comment]
Добрый день. Вы устанавливали python-библиотеку Яндекс.Музыки?
```
$ sudo dnf in python3-frozenlist python3-multidict python3-yarl
$ pip install yandex-music --upgrade
```

**Comment by VadimRight** [comment]
Нет, этой команды я не выполнил.
Спасибо за обратную связь.
