### ISSUE TITLE
Скрытие пароля

### ISSUE THREAD

**Issue by cka304huk-m** [dobroweb/rhythmbox-plugin-yandex-music#8]
Когда ввожу пароль он виден, а хотелось бы возможность его скрывать:
![изображение](https://user-images.githubusercontent.com/50353911/167701513-6b53431e-b937-4584-a6f6-da74362a85c2.png)

**Comment by cka304huk-m** [comment]
Распаковал из исходников и там уже реализовано.

**Comment by dobroweb** [comment]
Проблема устранена https://github.com/dobroweb/rhythmbox-plugin-yandex-music/commit/f6381131a6f08ad9410ca284316312247886536b
